import { z } from "zod";
import {
  id,
  text,
  name,
  revision,
  page,
  projectTaxonomyInput,
  projectTaxonomyOutput,
  projectInput,
  contextTextInput,
  contextTextOutput,
} from "../common.js";
import {
  threadOutput,
  projectOutput,
  instructionsOutput,
  documentOutput,
} from "../output-common.js";

const githubAppMetadata = z.object({
  id: z.string(),
  name: z.string(),
  slug: z.string(),
  owners: z.array(z.string()).max(20),
});

export const projectsInputs = {
  "github.apps": z.object({}),
  "projects.context.get": z.object({ projectId: id }),
  "projects.context.save": z.object({ projectId: id, ...contextTextInput }),
  "projects.list": z.object({}),
  "projects.create": projectInput,
  "projects.get": z.object({ projectId: id }),
  "projects.update": projectInput.extend({ projectId: id, revision }),
  "projects.taxonomy.get": z.object({ projectId: id }),
  "projects.taxonomy.update": projectTaxonomyInput,
  "documents.upload": z.object({
    projectId: id,
    name: z.string().trim().min(1).max(160),
    fileBase64: z.string().min(1).max(11184812),
    idempotencyKey: z.string().min(8).max(200),
  }),
  "documents.list": z.object({ projectId: id }),
  "documents.get": z.object({ documentId: id }),
  "documents.threads": z.object({
    documentId: id,
    page: z.number().int().min(1).max(25),
    cursor: id.optional(),
  }),
  "github.appSelect": z.object({
    projectId: id,
    revision,
    appId: z
      .string()
      .regex(/^[1-9]\d{0,19}$/)
      .nullable(),
  }),
  "github.connection": z.object({ projectId: id }),
  "github.issueState": z.object({ threadId: id }),
  "github.connect": z.object({ projectId: id, revision }),
  "github.disconnect": z.object({ projectId: id, revision }),
  "github.repositoryConnect": z.object({
    projectId: id,
    revision,
    repositoryUrl: z.string().url().max(1000),
  }),
  "github.repositoryDisconnect": z.object({
    projectId: id,
    revision,
    repositoryUrl: z.string().url().max(1000),
  }),
  "github.statusSyncConfigure": z.object({
    projectId: id,
    revision,
    enabled: z.boolean(),
  }),
  "github.statusSync": z.object({
    threadId: id,
    revision,
    issueUrl: z.string().url(),
    source: z.enum(["github", "feedbacks"]),
  }),
  "github.statusSyncState": z.object({ threadId: id }),
  "github.issueCreate": z.object({
    threadId: id,
    revision,
    repositoryUrl: z.string().url().max(1000).optional(),
    reviewed: z.literal(true),
    title: z.string().trim().min(1).max(120),
    body: z.string().trim().min(1).max(8000),
    idempotencyKey: z.string().min(8).max(200),
  }),
  "github.issueCreateQuick": z.object({
    threadId: id,
    revision,
    repositoryUrl: z.string().url().max(1000).optional(),
    idempotencyKey: z.string().min(8).max(200),
  }),
  "github.issueReconcile": z.object({
    threadId: id,
    revision,
    issueUrl: z.string().url(),
  }),
  "github.issueAbandon": z.object({
    threadId: id,
    revision,
    confirmedAbsent: z.literal(true),
  }),
  "github.issueRefresh": z.object({ threadId: id, revision, issueUrl: z.string().url() }),
  "webhooks.get": z.object({ projectId: id }),
  "webhooks.save": z.object({ projectId: id, url: z.string().url().max(2048) }),
  "webhooks.rotate": z.object({ projectId: id }),
  "webhooks.disable": z.object({ projectId: id }),
  "webhooks.deliveries": z.object({ projectId: id }),
  "qa.get": z.object({ projectId: id }),
  "qa.configure": z.object({
    projectId: id,
    enabled: z.boolean(),
    urls: z.array(z.string().url().max(500)).max(3),
  }),
  "qa.runNow": z.object({ projectId: id }),
  "qa.runs": z.object({ projectId: id }),
  "qa.baselineGet": z.object({ threadId: id }),
  "qa.baselineSet": z.object({ threadId: id, assetId: id }),
  "qa.compare": z.object({ threadId: id, assetId: id }),
  "instructions.get": z.object({ projectId: id }),
  "instructions.publish": z.object({
    projectId: id,
    body: text,
    revision: z.number().int().min(0),
  }),
};

export const projectsOutputs = {
  "github.apps": z.object({
    defaultAppId: z.string().nullable(),
    apps: z.array(githubAppMetadata).max(21),
  }),
  "projects.context.get": contextTextOutput,
  "projects.context.save": contextTextOutput,
  "documents.upload": documentOutput,
  "documents.list": z.object({ items: z.array(documentOutput) }),
  "documents.get": documentOutput,
  "documents.threads": z.object({
    page: z.number().int().positive(),
    cursor: id.nullable(),
    items: z.array(
      z.object({
        threadId: id,
        body: z.string(),
        page: z.number().int().positive(),
        x: z.number(),
        y: z.number(),
        state: z.string(),
      }),
    ),
    nextCursor: id.nullable(),
  }),
  "projects.list": z.object({ items: z.array(projectOutput) }),
  "projects.get": projectOutput,
  "projects.create": projectOutput,
  "projects.update": projectOutput,
  "projects.taxonomy.get": projectTaxonomyOutput,
  "projects.taxonomy.update": projectTaxonomyOutput.extend({ project: projectOutput }),
  "github.connection": z.object({
    appId: z.string().nullable(),
    appName: z.string().nullable(),
    approvedAccounts: z.array(z.string()).max(20),
    canSelectApp: z.boolean(),
    apps: z.array(githubAppMetadata).max(21),
    configured: z.boolean(),
    connected: z.boolean(),
    statusSyncEnabled: z.boolean(),
    repositoryUrl: z.string().nullable(),
    repositories: z
      .array(
        z.object({
          repositoryUrl: z.string().url(),
          connected: z.boolean(),
          installation: z.enum(["installed", "not_installed", "unavailable"]),
        }),
      )
      .max(21),
    installUrl: z.string().nullable(),
    installation: z.enum([
      "not_configured",
      "no_repository",
      "installed",
      "not_installed",
      "unavailable",
    ]),
  }),
  "github.issueState": z.object({
    status: z.enum(["none", "pending", "linked"]),
    issueUrl: z.string().nullable(),
    canAbandon: z.boolean(),
  }),
  "github.appSelect": projectOutput,
  "github.connect": projectOutput,
  "github.disconnect": projectOutput,
  "github.repositoryConnect": projectOutput,
  "github.repositoryDisconnect": projectOutput,
  "github.statusSyncConfigure": projectOutput,
  "github.statusSync": threadOutput,
  "github.statusSyncState": z.object({
    status: z.enum(["disabled", "pending", "ready", "conflict", "uncertain", "error"]),
    issueUrl: z.string().nullable(),
    feedbacksState: z.string().nullable(),
    githubState: z.enum(["open", "closed"]).nullable(),
    pendingTarget: z.enum(["open", "closed"]).nullable(),
    errorCode: z.string().nullable(),
  }),
  "github.issueCreate": threadOutput,
  "github.issueCreateQuick": threadOutput,
  "github.issueReconcile": threadOutput,
  "github.issueAbandon": z.object({ abandoned: z.boolean() }),
  "github.issueRefresh": threadOutput,
  "webhooks.get": z.object({
    configured: z.boolean(),
    url: z.string().nullable(),
    createdAt: z.string().nullable(),
    updatedAt: z.string().nullable(),
  }),
  "webhooks.save": z.object({
    configured: z.literal(true),
    url: z.string(),
    secret: z.string().optional(),
  }),
  "webhooks.rotate": z.object({
    configured: z.literal(true),
    url: z.string(),
    secret: z.string(),
  }),
  "webhooks.disable": z.object({ disabled: z.boolean() }),
  "webhooks.deliveries": z.object({
    items: z.array(
      z.object({
        id,
        status: z.enum(["pending", "delivered", "failed"]),
        attempts: z.number().int(),
        lastStatus: z.number().nullable(),
        createdAt: z.string(),
        deliveredAt: z.string().nullable(),
      }),
    ),
  }),
  "qa.get": z.object({
    enabled: z.boolean(),
    urls: z.array(z.string()),
    nextAt: z.string().nullable(),
  }),
  "qa.configure": z.object({
    enabled: z.boolean(),
    urls: z.array(z.string()),
    nextAt: z.string().nullable(),
  }),
  "qa.runNow": z.object({ queued: z.boolean() }),
  "qa.runs": z.object({
    items: z.array(
      z.object({
        id,
        createdAt: z.string(),
        pages: z.array(
          z.object({
            url: z.string(),
            status: z.number().nullable(),
            missingAlt: z.number().int(),
            brokenLinks: z.array(z.object({ path: z.string(), status: z.number() })),
            checkedLinks: z.number().int(),
            error: z.string().nullable(),
          }),
        ),
      }),
    ),
  }),
  "qa.baselineGet": z.object({ assetId: id.nullable(), setAt: z.string().nullable() }),
  "qa.baselineSet": z.object({ assetId: id, setAt: z.string() }),
  "qa.compare": z.object({
    baselineAssetId: id,
    candidateAssetId: id,
    width: z.number().int(),
    height: z.number().int(),
    changedPercent: z.number(),
  }),
  "instructions.get": instructionsOutput,
  "instructions.publish": instructionsOutput,
};
